packages:
  - 'csr/angular-webpack/'
  - 'csr/preact-webpack/'
  - 'csr/react-vite/'
  - 'csr/react-webpack/'
  - 'csr/solid-webpack/'
  - 'csr/static-page/'
  - 'csr/vue-vite/'
  - 'csr/vue-webpack/'
  - 'kolibri/library/app/'
  - 'kolibri/library/components/'
  - 'kolibri/library/components/adapters/angular/'
  - 'kolibri/library/components/adapters/react/'
  - 'kolibri/library/components/adapters/vue/'
  - 'kolibri/library/schema/'
  - 'kolibri/library/theme/'
  - 'kolibri/theme/'
  # - 'ssr/astro/'
  - 'ssr/express/'
  # - 'ssr/next.js/'
  # - 'ssr/remix/'
  - 'svg2font/'
