packages:
  # Client Side Rendering (CSR) Templates
  - 'csr/react-vite/'
  - 'csr/react-vite-react-hook-form/'
  - 'csr/react-vite-formik/'
  - 'csr/react-standalone/'
  - 'csr/static-page/'
  - 'csr/vue-vite/'

  # Server Side Rendering (SSR) Templates
  - 'ssr/express/'
  # Coming soon:
  # - 'ssr/astro/'
  # - 'ssr/next.js/'
  # - 'ssr/remix/'

  # KoliBri Library Templates
  # - 'kolibri/library/app/'
  - 'kolibri/library/components/'
  - 'kolibri/library/components/adapters/angular/'
  - 'kolibri/library/components/adapters/react/'
  - 'kolibri/library/components/adapters/vue/'
  - 'kolibri/library/schema/'
  - 'kolibri/library/theme/'
  - 'kolibri/theme/'

  # Utility Templates
  - 'svg2font/'
