name: Auto dependency updater

on:
  schedule:
    - cron: 0 2 * * *
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        id: pnpm-install
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache pnpm store
        id: pnpm-cache-step
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-store-

      # - name: Delete old branch if exists
      #   run: |
      #     git fetch origin
      #     git branch -D auto/update-deps || true
      #     git push origin --delete auto/update-deps || true

      - name: Create update branch
        run: git checkout -B auto/update-deps

      - name: Install
        run: pnpm i
      - name: Update dependencies
        run: pnpm ncu:minor
      - name: Reinstall dependencies
        run: pnpm i --frozen-lockfile

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v6
        with:
          branch: auto/update-dependencies
          title: 'chore: update dependencies'
          body: This PR updates all dependencies using `pnpm update`.
          commit-message: 'chore: update dependencies'
          author: GitHub Actions <actions@github.com>
          delete-branch: true
